//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mark
    {
        public string studentCode { get; set; }
        public int taskId { get; set; }
        public int mark1 { get; set; }
    
        public virtual Student Student { get; set; }
        public virtual Task Task { get; set; }
    }
}
